### ISSUE TITLE
Saw your linkedin message

### ISSUE THREAD

**Issue by rishiits** [philipturner/molecular-renderer#7]
got it, not going to use any derivatives of any repos you or atomcad have made. i'm sorry if you thought i was trying to take anything of significance from you, i'll only use open-access repos like nanoengineer or public python libraries etc if i'm doing computational work. just letting you know that you don't need to worry about that

**Comment by philipturner** [comment]
@rishiits you directly lied to me, or at least a reasonable person would infer you did. You tried to impersonate the maintainer of NanoEngineer and myself on LinkedIn (I haven't checked whether you corrected the profile). On top of that, your activity appeared to have ulterior motives. Your effort to create a wedge between me and other OSS contributors caused irreparable harm to my effort. I will not elaborate more on the side effects of your actions, as that is private information.

Whether or not you intended for this to happen, these are the consequences.
